---
version: 2.8.1
slug: stargate2
name: 星际之门 · StarGate（备选）
description: 星际之门的功能补充版本，适合首选版无法使用时替代。
url: https://github.com/v2raya
arch:
  - aarch64
  - amd64
hassio_api: true
host_network: true
image: ghcr.io/wuwweizn/stargate2-{arch}
init: false
boot: manual
map:
  - addons:rw
  - addon_config:rw
  - backup:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
  - ssl:rw
udev: true
ports_description:
  2017/tcp: "Web UI port"
webui: "http://[HOST]:[PORT:2017]/"
ports:
  2017/tcp: 2017
privileged:
  - SYS_ADMIN
  - NET_ADMIN
  - NET_RAW
  - DAC_READ_SEARCH
apparmor: true
devicetree: false
options:
  bin_app: v2ray-core
  clear_mode: false
schema:
  bin_app: list(v2ray-core|xray-core)
  clear_mode: bool
startup: services
