name: "节点小宝"
slug: "jdxb"
version: "3.0.5"
description: "节点小宝客户端"
arch:
  - amd64
  - aarch64
startup: services
boot: manual
init: false
host_network: true
image: "ghcr.io/wuwweizn/jdxb-{arch}"
ports:
  "9118/tcp": 9118
devices:
  - /dev/net/tun
restart: always
ingress: true
ingress_port: 9118
panel_icon: mdi:server-network
